--- 
 - name: Create a directory 
   file:
    path: /opt/tomcat
    state: directory

 - name: Extract tomcat
   unarchive:
    src: tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
    dest: /opt/tomcat/
    remote_src: yes
