---
# tasks file for myansibletomcat
  - include: installjava.yml
  - include: tomcatusergroup.yml
  - include: downloadtomcat.yml
  - include: extracttomcat.yml
  - include: tompermissions.yml
  - include: tomconfig.yml
  - include: tomstart.yml
  - include: tomuser.yml
  - include: tommanager.yml
  - include: tomhostanager.yml
  - include: tomrestart.yml
  - include: tomcatdeploy.yml
  - include: tomrestart.yml


