--- 
 - name:  create tomcat group 
   group:
    name: tomcat
    state: present

 - name: create tomcat user 
   user:
    name: tomcat
    shell: /bin/flase
    home: /opt/tomcat
    groups: tomcat
    